### PR TITLE
Implemente autocomplete

### PR DESCRIPTION
**Pull request by sanotto**
It will show an autocomplete menu with words allready present in the document. It is not intellisense just yet. To be "intellisense" the list should be filtered by context. This is a step into that direction but it is still usefull

### CODE REVIEW

**Comment by worksofliam** [comment]
@sanotto Thanks a lot for making a PR. I will review tomorrow and get this merged after some testing.

Thanks!!

**Comment by worksofliam** [comment]
I did some testing and it seems fairly buggy for now (see attached) - I will leave this open for a while until I have some time to play around with it,

Cheers! 

image

**Comment by sanotto** [comment]
I see...I've did just a Split(' ').. Obviously, it is more a proof of
concept than a finished contribution, I've rushed it to you to check if the
task was on the making by you (or not). I'll happily  look into it. There
are lot's of improvements to be made.


2017-11-26 19:34 GMT-03:00 Liam Allan <notifications@github.com>:

**Comment by sanotto** [comment]
Mr Allan:
                Please take a look at the fixes made into sanotto/idle
patch-1 in short:

* I've unified word detecting criteria in a RegEx, so parsing and detecting
current word uses the same criteria .
* I've added adefault autocompletion words taken of Resource/Autocomplete.
* The default word (Which are in uppercase) are replaced for the case
version in the document, thus if you type dcl-c, DCL-C gets replaced for
your favorite case

               I was working with PUB400.com but now it went  offline. The
IBM i in my organization is an ancient V6R1, IDLE does not work with it
because it use RUNSQL and select into table, both features  not supported
by my current release, so it will get a little difficult to keep working on
IDLE (Unless we find out a way to avoid RUNSQL/SELECT to table).

2017-11-26 19:49 GMT-03:00 santiago ottonello <sanotto@gmail.com>:

**Comment by worksofliam** [comment]
I love it. Thanks for making use of the AutoComplete files I made, I knew they would come in handy at some point. 

I think, for performance on low-end machines, we should make it so we require a Ctrl+Space for the autocomplete box to show and it will use the current typing word for the keyword (`autocompleDefaultList.Contains(uppercased_word)`). This would be similar to Eclipse.

`textEditor_TextArea_TextEntered` is being run for every character entered, and it's scanning through large lists - CL has a lot of commands 😄 

Also, sorry about the issue with pub400. I also used that box for the demo videos I made.. hoping they can make a recovery - if not, let me know and I will be happy to get an Idle development system for contributors to use.

What do you think @sanotto?

**Comment by sanotto** [comment]
Mr. Allan:
                    With regards of textEditor_TextArea_TextEntered I've
noticed the point you state, the best option to resolve the issue is to
make a full scan on document load and cache the word list (We need to make
that a set not al list) in the class, and then accumulate any char typed
until a non-word char is typed (i.e. blanks, colons etc.) at that point we
have a word, insert it in the "word-set", and empty the "word_collector"
variable, and problem solved, no more scanning with every char.

By the way, a set is not the best structure for the task either, the best
structure is a kind of tree structure, the "trie" if I'm not mistaken (
https://en.wikipedia.org/wiki/Trie)  I never used a "trie".  I think it is
overkill, even a really, really big rpgle source should not be a problem
for a modern machine and a "trie" is kind of over optimizing (But it is the
correct solution nonetheless).

If you could get me access to some system to keep working on this,
wonderfull!


2017-11-28 15:41 GMT-03:00 Liam Allan <notifications@github.com>:

**Comment by worksofliam** [comment]
@sanotto Correct about the 'trie'/'tree' - I did actually implement a terrible parser for RPG which would return a `TreeList[]` (we could change it to return a `string[]`) after parsing the file.

It starts here: https://github.com/WorksOfBarry/Idle/blob/master/ILEditor/Classes/LanguageTools/RPGParser.cs#L414

**Comment by worksofliam** [comment]
@sanotto Perhaps look into trying out a free IBM i here: https://www.nicklitten.com/free-ibm-i-system-for-developers/

**Comment by sanotto** [comment]
3eqewiñ33e

**Pull request closed without merging**
