### PR TITLE
Don't crash if the FTP fails, just return an error

### PR DESCRIPTION
**Pull request by kenwilcox**
This would fail on the second time I opened the remote dir

### CODE REVIEW

**Comment by kenwilcox** [comment]
I'm not sure why, but when I first open it /home/source fails, I attempt it a second time and /home/source works

**Comment by worksofliam** [comment]
Hi @kenwilcox 

Thanks for the PR! Just to confirm, does it maintain the connection after it has crashed?

You are not the first person to notice this issue (#40).

Let me know, and I will test and merge!

Edit: This may be something to raise with the FTP library also. If possible, grab a call stack of the crash and paste it here so I can pass it on!

**Comment by kenwilcox** [comment]
Sorry - I didn't see issue #40 - that's the same one a co worker was seeing. Without the try catch you get the following crash stack:

FluentFTP.FtpException
  HResult=0x80131500
  Message=DirectoryExists(): Failed to restore the working directory.
  Source=FluentFTP
  StackTrace:
   at FluentFTP.FtpClient.DirectoryExists(String path)
   at ILEditor.Classes.IBMi.DirExists(String remoteDir) in C:\Users\wilcoxk\Documents\GitHub\ILEditor\ILEditor\Classes\IBMi.cs:line 250
   at ILEditor.UserTools.IFSBrowser.<>c__DisplayClass2_0.<IFSBrowser_Load>b__0() in C:\Users\wilcoxk\Documents\GitHub\ILEditor\ILEditor\UserTools\IFSBrowser.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

with the return false the app doesn't crash, it just says the directory doesn't exist. On the second attempt it connects, stays open and works just fine. I checked out several source files.

Here's a video that might help explain it better than words (sorry it's not edited)

https://www.dropbox.com/s/rcozst1fgdfkrfl/ILEditor.mp4?dl=0

**Comment by worksofliam** [comment]
@kenwilcox 

Thanks for the video. That explains it perfectly. I am happy with the fix, but can you also make a call to `Editor.TheEditor.SetStatus(string)` in the `catch` to say that the user should retry opening the IFS tool again?

This is an error with the FTP library, in which I will raise an issue with that library.

Cheers,
Liam

**Comment by kenwilcox** [comment]
What verbiage would you like it to say? Just exception.Message? which is "DirectoryExists(): Failed to restore the working directory."

I thought maybe a "please try again" at the end might help

**Comment by worksofliam** [comment]
Thank you @kenwilcox for your PR. 

I will fix up the message for you! Please let me know if there is anything else I can do for you.

**Comment by kenwilcox** [comment]
Thanks for making this - I think it's going to be great!

**Pull request merged**
